import { jsPDF } from 'jspdf';
import { GROWTHIQ_BRAND } from '../data/growthiqConstants';

const LIME = [200, 245, 66];
const DARK = [17, 17, 19];
const MUTED = [102, 102, 102];

function addHeader(doc, business, reportId) {
  doc.setFillColor(...DARK);
  doc.rect(0, 0, 210, 42, 'F');
  doc.setTextColor(...LIME);
  doc.setFontSize(10);
  doc.text('weROI', 14, 14);
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.text(`${GROWTHIQ_BRAND} Report`, 14, 26);
  doc.setFontSize(9);
  doc.setTextColor(200, 200, 200);
  doc.text(business, 14, 34);
  doc.text(`Report ID: ${reportId}`, 140, 34);
}

function addSectionTitle(doc, y, title) {
  doc.setTextColor(...DARK);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 14, y);
  doc.setDrawColor(...LIME);
  doc.setLineWidth(0.8);
  doc.line(14, y + 2, 196, y + 2);
  return y + 10;
}

function addWrapped(doc, text, x, y, maxWidth, lineHeight = 5) {
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(50, 50, 50);
  const lines = doc.splitTextToSize(text || '', maxWidth);
  doc.text(lines, x, y);
  return y + lines.length * lineHeight + 2;
}

function addFieldRow(doc, label, value, y) {
  if (!value) return y;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text(label, 14, y);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...DARK);
  return addWrapped(doc, String(value), 14, y + 4, 182, 4.5);
}

export async function downloadGrowthIQPdf({ report, assessment, reportId }) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const r = report || {};
  const a = assessment || {};
  const business = a.business_name || 'Your Business';
  const summary = r.report_summary || {};

  addHeader(doc, business, reportId);

  let y = 52;
  doc.setFillColor(248, 248, 246);
  doc.roundedRect(14, y - 6, 182, 28, 3, 3, 'F');
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...DARK);
  doc.text(String(r.overall_score || 0), 24, y + 10);
  doc.setFontSize(10);
  doc.setTextColor(...MUTED);
  doc.text('/ 100', 44, y + 10);
  doc.setFontSize(14);
  doc.setTextColor(...DARK);
  doc.text(`${r.letter_grade || ''} · ${r.growth_level || ''}`, 24, y + 18);
  if (summary.overall_meaning) {
    doc.setFontSize(8);
    doc.setTextColor(70, 70, 70);
    y = addWrapped(doc, summary.overall_meaning, 70, y + 4, 120, 4);
  } else {
    y += 28;
  }
  y += 12;

  if (y > 250) { doc.addPage(); y = 20; }

  y = addSectionTitle(doc, y, 'Your submission');
  const presence = a.digital_presence || {};
  const presenceSummary = Object.entries(presence)
    .filter(([, v]) => v)
    .map(([k, v]) => `${k.replace(/_/g, ' ')}: ${v}`)
    .join('; ');

  y = addFieldRow(doc, 'Contact', `${a.full_name || ''} · ${a.business_email || ''} · ${a.phone || ''}`, y);
  y = addFieldRow(doc, 'Business', `${a.business_name || ''} · ${a.industry || ''} · ${a.business_size || ''}`, y);
  y = addFieldRow(doc, 'Location & goal', `${a.country || ''} · Primary goal: ${a.primary_goal || ''}`, y);
  y = addFieldRow(doc, 'Website', a.website || a.website_url || 'Not provided', y);
  y = addFieldRow(doc, 'Digital presence', presenceSummary, y);
  y = addFieldRow(doc, 'Goals & context', a.business_goals, y);

  if (r.executive_summary) {
    if (y > 240) { doc.addPage(); y = 20; }
    y = addSectionTitle(doc, y + 4, 'Executive summary');
    y = addWrapped(doc, r.executive_summary, 14, y, 182);
  }

  (r.categories || []).forEach((cat) => {
    if (y > 230) { doc.addPage(); y = 20; }
    y = addSectionTitle(doc, y + 6, `${cat.label}: ${cat.score}/100 (${cat.score_label || ''})`);
    if (cat.finding) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(...DARK);
      doc.text('Finding', 14, y);
      y = addWrapped(doc, cat.finding, 14, y + 4, 182);
    }
    if (cat.recommendation) {
      doc.setFont('helvetica', 'bold');
      doc.text('Recommendation', 14, y);
      y = addWrapped(doc, cat.recommendation, 14, y + 4, 182);
    }
    if (cat.weroi_help) {
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...MUTED);
      doc.text('How weROI can help', 14, y);
      y = addWrapped(doc, cat.weroi_help, 14, y + 4, 182);
    }
  });

  if (summary.priority_areas?.length) {
    if (y > 240) { doc.addPage(); y = 20; }
    y = addSectionTitle(doc, y + 6, 'Priority areas');
    summary.priority_areas.forEach((item) => {
      y = addWrapped(doc, `• ${item}`, 14, y, 182, 4.5);
    });
  }

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i += 1) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text(`Generated by ${GROWTHIQ_BRAND} · weroi.net`, 14, 290);
    doc.text(`Page ${i} of ${pageCount}`, 180, 290);
  }

  doc.save(`weROI-GrowthIQ-${business.replace(/\s+/g, '-')}-${reportId.slice(0, 8)}.pdf`);
}
